version: "2.1"
services:
  opbeans-node:
    build: .
    image: opbeans/opbeans-node:latest
    ports:
      - "127.0.0.1:${OPBEANS_NODE_PORT:-8000}:3000"
    container_name: opbeans-node
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    environment:
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-node}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
      - ELASTIC_APM_APPLICATION_PACKAGES=co.elastic.apm.opbeans
      - ELASTIC_APM_JS_SERVER_URL=${ELASTIC_APM_JS_SERVER_URL:-http://localhost:8200}
      - ELASTIC_APM_JS_SERVICE_NAME=${ELASTIC_APM_JS_SERVICE_NAME:-opbeans-react}
      - NODE_ENV=production
      - OPBEANS_SERVER_PORT=${OPBEANS_SERVER_PORT:-3000}
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=hunter2
      - PGDATABASE=opbeans
      - REDIS_URL=redis://redis:6379
      - OTEL_RESOURCE_ATTRIBUTES=service.name=${ELASTIC_APM_SERVICE_NAME:-opbeans-node},deployment.environment=production
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://apm-server:8200}
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - APM_AGENT_TYPE=${APM_AGENT_TYPE:-elasticapm}
    depends_on:
      apm-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--server-response", "-O", "/dev/null", "http://opbeans-node:3000/"]
      interval: 10s
      retries: 10

  apm-server:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION:-7.3.0}
    ports:
      - "127.0.0.1:${APM_SERVER_PORT:-8200}:8200"
      - "127.0.0.1:${APM_SERVER_MONITOR_PORT:-6060}:6060"
    command: >
      apm-server -e
        -E apm-server.frontend.enabled=true
        -E apm-server.frontend.rate_limit=100000
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.read_timeout=1m
        -E apm-server.shutdown_timeout=2m
        -E apm-server.write_timeout=1m
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E xpack.monitoring.elasticsearch=true
        -E output.elasticsearch.username=apm_server_user
        -E output.elasticsearch.password=changeme
        -E output.elasticsearch.enabled=${APM_SERVER_ELASTICSEARCH_OUTPUT_ENABLED:-true}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://apm-server:8200/"]
      retries: 10
      interval: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-7.3.0}
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms"]
      retries: 300
      interval: 1s
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "network.host="
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "discovery.type=single-node"
      - "xpack.security.authc.anonymous.roles=remote_monitoring_collector"
      - "xpack.security.authc.realms.file.file1.order=0"
      - "xpack.security.authc.realms.native.native1.order=1"
      - "xpack.security.enabled=true"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.authc.token.enabled=true"
      - "xpack.security.authc.api_key.enabled=true"
      - "logger.org.elasticsearch=${ES_LOG_LEVEL:-error}"
      - "action.destructive_requires_name=false"
    volumes:
      - "./config/elasticsearch/roles.yml:/usr/share/elasticsearch/config/roles.yml"
      - "./config/elasticsearch/users:/usr/share/elasticsearch/config/users"
      - "./config/elasticsearch/users_roles:/usr/share/elasticsearch/config/users_roles"

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION:-7.3.0}
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q 'All services are available'"]
      retries: 300
      interval: 1s
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: "${KIBANA_ES_USER:-kibana_system_user}"
      ELASTICSEARCH_PASSWORD: "${KIBANA_ES_PASS:-changeme}"
      XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      XPACK_FLEET_REGISTRYURL: "https://epr-snapshot.elastic.co"
      XPACK_SECURITY_LOGINASSISTANCEMESSAGE": "Login&#32;details:&#32;`admin/changeme`."
    depends_on:
      elasticsearch: { condition: service_healthy }
    volumes:
      - "./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"

  fleet_setup:
      command:
      - curl
      - -X
      - POST
      - -H
      - "kbn-xsrf: 1"
      - "http://admin:changeme@kibana:5601/api/fleet/setup"
      depends_on:
        kibana:
          condition: "service_healthy"
      image: "docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-7.3.0}"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_DB=opbeans
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 10
      interval: 10s

  redis:
    image: redis:4
    ports:
      - 6379:6379
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  wait:
    image: busybox
    depends_on:
      opbeans-node:
        condition: service_healthy

  loadPgData:
    image: node:12-bullseye
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=hunter2
      - PGDATABASE=opbeans
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    command: ["/bin/bash","-c","apt-get update && apt-get install -qq -y postgresql-client && npm install && npm run db-setup && node db/generate_orders.js 1000"]
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
